name: Create Release and Push Docker Image

on:
  workflow_dispatch:
    

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check GITHUB_TOKEN secret
        run: echo ${{ secrets.GITHUB_TOKEN }}
      - name: github ref 
        run: echo ${{ github.ref }}
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.2.0 # replace with the tag name you want to use
          release_name: Release v1.2.0 # replace with the release name you want to use
          body: Automated release created by GitHub Actions
          draft: false
          prerelease: false

  push-docker-image:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            rayahh/3tier-front:${{ steps.create-release.outputs.tag_name }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
